// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://eayqsqwtxwftnqbkuyip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVheXFzcXd0eHdmdG5xYmt1eWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3OTU0MjEsImV4cCI6MjEwNDM3MTQyMX0.Gd5tGq-qY8sauNYNXgfNCsnR2IBRRugiVVlbfOdUPas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});